[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[package.metadata.clippy]
extra_args = ["--warn=clippy::pedantic", "--warn=clippy::nursery", "--warn=clippy::cargo"]

[[bin]]
name = "day01"
path = "src/bin/day01.rs"
